"use client";
import {FormEvent,useEffect,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowLeft,Calculator,CheckCircle2,GitMerge,History,ReceiptText,TriangleAlert,X} from "lucide-react";
import {useParams} from "next/navigation";
import {Shell} from "@/components/shell";
import {Dialog} from "@/components/dialog";
import {Money} from "@/components/status";
import {Account,api} from "@/lib/api";

type Tx={id:string;description:string;merchant:string;amount:string;direction:string;date:string;pending:boolean;category:string;data_source:string};
type Candidate={key:string;transactions:Tx[]};
type DuplicateMergeChoice={keep:Tx;duplicate:Tx};
type Preview={account:{id:string;name:string;kind:string;mask:string};period_start:string;period_end:string;opening_balance:string;closing_balance:string;credits_total:string;debits_total:string;calculated_closing_balance:string;difference:string;balanced:boolean;balance_mode:string;formula:string;difference_explanation:string;transaction_count:number;pending_count:number;duplicate_candidates:Candidate[];transactions:Tx[]};
type Reconciliation={id:string;account_id:string;period_start:string;period_end:string;opening_balance:string;closing_balance:string;credits_total:string;debits_total:string;calculated_closing_balance:string;difference:string;transaction_count:number;pending_count:number;reconciled_at:string;notes:string};
const today=new Date().toISOString().slice(0,10);
const firstOfMonth=today.slice(0,8)+"01";
const day=(value:string)=>new Date(value+(value.includes("T")?"":"T12:00:00")).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"});

export default function ReconcileAccountPage(){
 const {accountId}=useParams<{accountId:string}>();const qc=useQueryClient();
 const [periodStart,setPeriodStart]=useState(firstOfMonth),[periodEnd,setPeriodEnd]=useState(today),[opening,setOpening]=useState(""),[closing,setClosing]=useState(""),[notes,setNotes]=useState(""),[message,setMessage]=useState("");
 const [missingDate,setMissingDate]=useState(today),[missingDescription,setMissingDescription]=useState(""),[missingAmount,setMissingAmount]=useState(""),[missingDirection,setMissingDirection]=useState("debit");
 const [duplicateMergeChoice,setDuplicateMergeChoice]=useState<DuplicateMergeChoice|null>(null);
 const accounts=useQuery({queryKey:["accounts"],queryFn:()=>api<Account[]>("/api/v1/accounts")});const account=accounts.data?.find(row=>row.id===accountId);
 const history=useQuery({queryKey:["reconciliations",accountId],queryFn:()=>api<Reconciliation[]>(`/api/v1/reconciliations/${accountId}`)});
 useEffect(()=>{if(!account)return;setClosing(current=>current||account.balance);if(account.balance_as_of_date){setPeriodEnd(account.balance_as_of_date);setMissingDate(account.balance_as_of_date);setPeriodStart(account.balance_as_of_date.slice(0,8)+"01")}},[account]);
 function body(){return {account_id:accountId,period_start:periodStart,period_end:periodEnd,opening_balance:opening,closing_balance:closing,notes}}
 const calculate=useMutation({mutationFn:()=>api<Preview>("/api/v1/reconciliations/preview",{method:"POST",body:JSON.stringify(body())}),onSuccess:()=>setMessage(""),onError:()=>setMessage("")});
 const complete=useMutation({mutationFn:()=>api<Reconciliation>("/api/v1/reconciliations",{method:"POST",body:JSON.stringify(body())}),onSuccess:()=>{setMessage("Period reconciled successfully.");qc.invalidateQueries({queryKey:["reconciliations",accountId]})}});
 const merge=useMutation({mutationFn:({keep,duplicate}:{keep:string;duplicate:string})=>api("/api/v1/reconciliations/merge",{method:"POST",body:JSON.stringify({keep_transaction_id:keep,duplicate_transaction_id:duplicate})}),onSuccess:()=>{setDuplicateMergeChoice(null);setMessage("Duplicate merged. The removed row remains in the audit history.");qc.invalidateQueries({queryKey:["transactions"]});calculate.mutate()}});
 const addMissing=useMutation({mutationFn:()=>api("/api/v1/reconciliations/transactions",{method:"POST",body:JSON.stringify({account_id:accountId,posted_date:missingDate,description:missingDescription,amount:missingAmount,direction:missingDirection})}),onSuccess:()=>{setMessage("Missing transaction added and labeled as a reconciliation entry.");setMissingDescription("");setMissingAmount("");qc.invalidateQueries({queryKey:["transactions"]});calculate.mutate()}});
 function submit(event:FormEvent){event.preventDefault();setMessage("");calculate.mutate()}
 function mergePair(keep:Tx,duplicate:Tx){setDuplicateMergeChoice({keep,duplicate})}
 const preview=calculate.data;const error=calculate.error||complete.error||merge.error||addMissing.error||accounts.error||history.error;
 return <Shell>
  <div className="page-title reconcile-title"><div><a className="back-link" href="/accounts"><ArrowLeft size={15}/>Accounts</a><p className="eyebrow">Account controls</p><h1>Reconcile {account?.name||"account"}</h1><p className="subtitle">Verify that settled transactions explain the movement between statement balances.</p></div>{account&&<span className="history-period">•••• {account.mask}</span>}</div>
  {accounts.isLoading?<div className="skeleton-page"><div/><div/></div>:!account?<div className="empty"><TriangleAlert/><h2>Account unavailable</h2><p>This account may have been archived.</p></div>:<div className="reconcile-stack">
   <section className="panel reconcile-intro"><div><Calculator/><div><h2>Statement balances</h2><p>Use the opening and closing balances printed on the same statement. Pending transactions are shown but excluded from the equation.</p></div></div><form className="reconcile-form" onSubmit={submit}><label>Period start<input required type="date" value={periodStart} onChange={event=>setPeriodStart(event.target.value)}/></label><label>Period end<input required type="date" value={periodEnd} onChange={event=>setPeriodEnd(event.target.value)}/></label><label>Opening balance<input required type="number" step="0.01" value={opening} onChange={event=>setOpening(event.target.value)} placeholder="0.00"/></label><label>Statement closing balance<input required type="number" step="0.01" value={closing} onChange={event=>setClosing(event.target.value)} placeholder="0.00"/></label><label className="reconcile-notes">Notes<textarea maxLength={500} value={notes} onChange={event=>setNotes(event.target.value)} placeholder="Optional statement reference or review note"/></label><button className="primary" disabled={calculate.isPending}>{calculate.isPending?"Calculating…":"Calculate difference"}</button></form></section>
   {error&&<div className="error-box" role="alert">{error instanceof Error?error.message:"Reconciliation could not be completed."}</div>}
   {message&&<div className="import-result"><p>{message}</p></div>}
   {preview&&<><section className={`panel reconcile-summary ${preview.balanced?"balanced":"out-of-balance"}`}><div className="panel-head"><div><p className="eyebrow">{preview.formula}</p><h2>{preview.balanced?"Reconciled to the cent":"Difference needs review"}</h2><p>{preview.difference_explanation}</p></div>{preview.balanced?<CheckCircle2/>:<TriangleAlert/>}</div><div className="reconcile-equation"><div><span>Opening</span><strong><Money value={preview.opening_balance}/></strong></div><b>{preview.balance_mode==="asset"?"+ credits":"+ debits"}</b><div><span>{preview.balance_mode==="asset"?"Credits":"Debits"}</span><strong><Money value={preview.balance_mode==="asset"?preview.credits_total:preview.debits_total}/></strong></div><b>{preview.balance_mode==="asset"?"− debits":"− credits"}</b><div><span>{preview.balance_mode==="asset"?"Debits":"Credits"}</span><strong><Money value={preview.balance_mode==="asset"?preview.debits_total:preview.credits_total}/></strong></div><b>=</b><div><span>Calculated closing</span><strong><Money value={preview.calculated_closing_balance}/></strong></div></div><div className="reconcile-difference"><span>Statement closing <Money value={preview.closing_balance}/></span><strong>Difference <Money value={preview.difference}/></strong></div><div className="reconcile-summary-actions"><span>{preview.transaction_count} settled · {preview.pending_count} pending excluded</span><a className="secondary" href={"/accounts?account_id="+accountId+"\&date_from="+periodStart+"\&date_to="+periodEnd}><ReceiptText/>Review transactions</a><button className="primary" disabled={!preview.balanced||complete.isPending} onClick={()=>complete.mutate()}>{complete.isPending?"Saving…":"Mark period reconciled"}</button></div></section>
   {!preview.balanced&&<section className="panel reconcile-missing"><div className="panel-head"><div><h2>Add missing activity</h2><p>Use this only for a real statement transaction that is absent from FinLeash. It will be labeled as a reconciliation entry.</p></div><ReceiptText/></div><form onSubmit={event=>{event.preventDefault();addMissing.mutate()}}><label>Posted date<input required type="date" min={periodStart} max={periodEnd} value={missingDate} onChange={event=>setMissingDate(event.target.value)}/></label><label>Description<input required maxLength={255} value={missingDescription} onChange={event=>setMissingDescription(event.target.value)} placeholder="Bank fee or interest credit"/></label><label>Amount<input required type="number" min="0.01" step="0.01" value={missingAmount} onChange={event=>setMissingAmount(event.target.value)} placeholder="0.00"/></label><label>Direction<select value={missingDirection} onChange={event=>setMissingDirection(event.target.value)}><option value="debit">Debit</option><option value="credit">Credit</option></select></label><button className="secondary" disabled={addMissing.isPending}>{addMissing.isPending?"Adding…":"Add transaction"}</button></form></section>}
   <section className="panel reconcile-candidates"><div className="panel-head"><div><h2>Possible duplicates</h2><p>Only same-account transactions with the same date, amount, direction, and compatible descriptions appear here.</p></div><GitMerge/></div>{preview.duplicate_candidates.length?preview.duplicate_candidates.map(group=><article key={group.key} className="duplicate-group">{group.transactions.map(tx=><div key={tx.id}><div><strong>{tx.merchant}</strong><p>{tx.description}</p><small>{day(tx.date)} · {tx.data_source} · {tx.category}</small></div><strong>{tx.direction==="credit"?"+":"−"}<Money value={tx.amount}/></strong></div>)}{group.transactions.length===2?<div className="duplicate-actions"><span>Choose the transaction details to keep:</span>{group.transactions.map((keep,index)=>{const duplicate=group.transactions[1-index];const sameLabel=keep.merchant===duplicate.merchant&&keep.description===duplicate.description;return <button type="button" key={keep.id} disabled={merge.isPending} onClick={()=>mergePair(keep,duplicate)}>{sameLabel?("Keep "+(index===0?"first":"second")+" row"):("Keep "+keep.merchant)}</button>})}</div>:<p className="field-help">More than two transactions share these values. Review them from the Transactions page instead of merging automatically.</p>}</article>):<div className="empty compact"><CheckCircle2/><h2>No likely duplicates detected</h2><p>Other differences can come from missing activity, posting dates, or pending transactions.</p></div>}</section>
   <details className="panel reconcile-transactions"><summary><span><ReceiptText/>Transactions in this period</span><strong>{preview.transactions.length}</strong></summary><div>{preview.transactions.map(tx=><article key={tx.id}><div><strong>{tx.merchant}</strong><span>{day(tx.date)} · {tx.category} · {tx.data_source}{tx.pending?" · pending":""}</span></div><strong className={tx.direction==="credit"?"transaction-credit":""}>{tx.direction==="credit"?"+":"−"}<Money value={tx.amount}/></strong></article>)}</div></details></>}
   <section className="panel reconciliation-history"><div className="panel-head"><div><h2>Reconciliation history</h2><p>Completed periods are retained as financial audit snapshots.</p></div><History/></div>{history.data?.length?history.data.map(row=><article key={row.id}><CheckCircle2/><div><strong>{day(row.period_start)} – {day(row.period_end)}</strong><p>{row.transaction_count} settled transactions · completed {day(row.reconciled_at)}</p>{row.notes&&<small>{row.notes}</small>}</div><div><span>Closing balance</span><strong><Money value={row.closing_balance}/></strong></div></article>):<div className="empty compact"><p>No completed reconciliation periods yet.</p></div>}</section>
  </div>}
 {duplicateMergeChoice&&<Dialog title="Merge duplicate transaction" onClose={()=>{if(!merge.isPending)setDuplicateMergeChoice(null)}} className="duplicate-merge-dialog"><div className="modal-head"><div><p className="eyebrow">Review duplicate</p><h2>Merge these transactions?</h2><p>Confirm which provider record should remain in your active transaction history.</p></div><button type="button" className="icon-button" aria-label="Close" disabled={merge.isPending} onClick={()=>setDuplicateMergeChoice(null)}><X/></button></div><div className="duplicate-merge-compare"><article className="duplicate-keep"><span>Keep</span><strong>{duplicateMergeChoice.keep.merchant}</strong><small>{day(duplicateMergeChoice.keep.date)} · {duplicateMergeChoice.keep.data_source}</small><b>{duplicateMergeChoice.keep.direction==="credit"?"+":"−"}<Money value={duplicateMergeChoice.keep.amount}/></b></article><article className="duplicate-remove"><span>Remove duplicate</span><strong>{duplicateMergeChoice.duplicate.merchant}</strong><small>{day(duplicateMergeChoice.duplicate.date)} · {duplicateMergeChoice.duplicate.data_source}</small><b>{duplicateMergeChoice.duplicate.direction==="credit"?"+":"−"}<Money value={duplicateMergeChoice.duplicate.amount}/></b></article></div><div className="whatif-note"><GitMerge/><p>The removed provider identity stays in the audit history and is blocked from reappearing during later syncs.</p></div>{merge.error&&<div className="error-box" role="alert">{merge.error instanceof Error?merge.error.message:"The duplicate could not be merged."}</div>}<div className="modal-actions"><button type="button" className="secondary" disabled={merge.isPending} onClick={()=>setDuplicateMergeChoice(null)}>Cancel</button><button type="button" className="danger-button" disabled={merge.isPending} onClick={()=>merge.mutate({keep:duplicateMergeChoice.keep.id,duplicate:duplicateMergeChoice.duplicate.id})}>{merge.isPending?"Merging…":"Merge duplicate"}</button></div></Dialog>}
 </Shell>
}
