from alembic import op
import sqlalchemy as sa
revision='0018';down_revision='0017';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('financial_connections',sa.Column('id',sa.String(36),primary_key=True),sa.Column('household_id',sa.String(36),sa.ForeignKey('households.id'),nullable=False),sa.Column('provider',sa.String(30),nullable=False),sa.Column('encrypted_access_url',sa.Text(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('last_sync_at',sa.DateTime(timezone=True)),sa.Column('last_successful_sync_at',sa.DateTime(timezone=True)),sa.Column('last_error',sa.String(255),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('data_source',sa.String(32),nullable=False),sa.Column('dml_flag',sa.String(1),nullable=False))
 op.create_index('ix_financial_connections_household_id','financial_connections',['household_id']);op.create_index('ix_financial_connections_provider','financial_connections',['provider']);op.create_index('ix_connection_household_provider','financial_connections',['household_id','provider'])
 op.add_column('financial_accounts',sa.Column('connection_id',sa.String(36),sa.ForeignKey('financial_connections.id')));op.add_column('financial_accounts',sa.Column('provider_account_id',sa.String(255)));op.create_index('ix_financial_accounts_connection_id','financial_accounts',['connection_id']);op.create_unique_constraint('uq_account_connection_provider','financial_accounts',['connection_id','provider_account_id'])
def downgrade():
 op.drop_constraint('uq_account_connection_provider','financial_accounts',type_='unique');op.drop_index('ix_financial_accounts_connection_id',table_name='financial_accounts');op.drop_column('financial_accounts','provider_account_id');op.drop_column('financial_accounts','connection_id');op.drop_index('ix_connection_household_provider',table_name='financial_connections');op.drop_index('ix_financial_connections_provider',table_name='financial_connections');op.drop_index('ix_financial_connections_household_id',table_name='financial_connections');op.drop_table('financial_connections')
