"use client";

import {Fragment,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ArrowRight,CalendarClock,ChevronRight,CircleAlert,Info,Landmark,Repeat2,ShieldCheck,Sparkles,WalletCards,X} from "lucide-react";
import {Dialog} from "@/components/dialog";
import {Shell} from "@/components/shell";
import {Money,Status} from "@/components/status";
import {api,TodayData} from "@/lib/api";

type MatchCandidate={id:string;merchant:string;description:string;amount:string;date:string;account_name:string;account_matches:boolean;confidence:string;reason:string};
type FlowEvent={id:string;date:string;kind:"income"|"payment";name:string;amount:string;account_id:string|null;detail:string;coverage_status?:string;balance_after?:string|null;income_status?:"estimated"|"received"|"not_confirmed"|"missing";reason?:string};
const incomeLabels={estimated:"Estimated",received:"Received",not_confirmed:"Not confirmed",missing:"Missing"};
const formatDate=(value:string,options:Intl.DateTimeFormatOptions)=>new Date(value+"T12:00").toLocaleDateString("en-US",options);
function Skeleton(){return <div className="skeleton-page"><div/><div/><div/><div/></div>}

export default function Today(){
  const qc=useQueryClient(),[matching,setMatching]=useState<{id:string;payee:string}|null>(null),[matchError,setMatchError]=useState("");
  const {data,error,isLoading}=useQuery({queryKey:["today"],queryFn:()=>api<TodayData>("/api/v1/today")});
  const candidates=useQuery({queryKey:["payment-match-candidates",matching?.id],queryFn:()=>api<MatchCandidate[]>("/api/v1/payments/"+matching!.id+"/match-candidates"),enabled:!!matching});
  const confirmMatch=useMutation({mutationFn:(row:MatchCandidate)=>api("/api/v1/payments/"+matching!.id+"/reconcile",{method:"POST",body:JSON.stringify({transaction_id:row.id,confirm_account_change:!row.account_matches})}),onSuccess:()=>{setMatching(null);setMatchError("");qc.invalidateQueries({queryKey:["today"]});qc.invalidateQueries({queryKey:["monthly-plan"]})},onError:e=>setMatchError(e.message)});
  if(isLoading)return <Shell><Skeleton/></Shell>;
  if(error||!data)return <Shell><div className="empty"><CircleAlert/><h2>We couldn’t load your plan</h2><p>{error instanceof Error?error.message:"Try again in a moment."}</p></div></Shell>;
  const attention=data.counts.at_risk+data.counts.unfunded;
  const monthLabel=formatDate(data.period_start,{month:"long",year:"numeric"});
  const flow:FlowEvent[]=[
    ...data.income.map(item=>({id:`income-${item.id}`,date:item.date,kind:"income" as const,name:item.name,amount:item.amount,account_id:item.account_id,detail:item.status==="received"?`Actual deposit${item.actual_date?` · posted ${formatDate(item.actual_date,{month:"short",day:"numeric"})}`:""}`:`Estimated $${Number(item.amount).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})} · expected ${formatDate(item.date,{month:"short",day:"numeric"})}`,balance_after:item.balance_after,income_status:item.status,reason:item.reason})),
    ...data.payments.map(item=>({id:item.id,date:item.withdrawal_date,kind:"payment" as const,name:item.payee,amount:item.amount,account_id:item.account_id,detail:item.method.replaceAll("_"," "),coverage_status:item.coverage_status,balance_after:item.balance_after}))
  ].sort((a,b)=>a.date.localeCompare(b.date)||(a.kind==="income"?-1:b.kind==="income"?1:a.name.localeCompare(b.name)));
  const todayISO=new Date().toLocaleDateString("en-CA");
  const firstUpcoming=flow.findIndex(event=>event.date>=todayISO);
  // Index in the timeline where the "Today" divider belongs; -1 when today is outside the forecast period.
  const todayMarkerIndex=todayISO>=data.period_start&&todayISO<=data.period_end?(firstUpcoming===-1?flow.length:firstUpcoming):-1;
  const rowState=(date:string)=>date<todayISO?" past":date===todayISO?" is-today":"";
  const todayMarker=<div className="timeline-today" role="separator"><span>Today · {formatDate(todayISO,{weekday:"short",month:"short",day:"numeric"})}</span></div>;

  return <Shell attention={attention}>
    <section className={`answer ${attention?"warning":"good"}`}><div className="answer-icon">{attention?<CircleAlert/>:<ShieldCheck/>}</div><div><span>Your answer for {monthLabel}</span><h2>{data.status}</h2><p>{data.reason}</p></div><a href="/monthly-plan">See what needs attention <ChevronRight/></a></section>
    <section className="stats-grid"><article><div className="stat-icon teal"><WalletCards/></div><p>Available cleared cash</p><strong><Money value={data.available_cash}/></strong><span>Across checking and savings</span></article><article><div className="stat-icon navy"><CalendarClock/></div><p>{monthLabel} payments</p><strong><Money value={data.scheduled_total}/></strong><span>Scheduled through month-end</span></article><article><div className="stat-icon gold"><Landmark/></div><p>Next reliable income</p><strong>{data.next_income_date?formatDate(data.next_income_date,{month:"short",day:"numeric"}):"Not scheduled"}</strong><span>High-confidence or guaranteed</span></article><article><div className="stat-icon blue"><ShieldCheck/></div><p>Protected reserve</p><strong><Money value={data.protected_reserve}/></strong><span>Not available for planning</span></article></section>
    <div className="content-grid"><section className="panel timeline"><div className="panel-head"><div><h2>{monthLabel} payment flow</h2><p>{formatDate(data.period_start,{month:"short",day:"numeric"})}–{formatDate(data.period_end,{month:"short",day:"numeric"})} · Income and payments simulated in date order</p></div><span className="estimate">Month forecast</span></div><div className="timeline-list">{flow.map((event,index)=><Fragment key={event.id}>{index===todayMarkerIndex&&todayMarker}{event.kind==="income"?<div className={`timeline-row flow-income income-${event.income_status}${rowState(event.date)}`} title={event.reason}><div className="date-box"><b>{formatDate(event.date,{day:"numeric"})}</b><span>{formatDate(event.date,{month:"short"})}</span></div><div className="timeline-dot"><i/><span/></div><div className="event-main"><strong>{event.name}</strong><span>{data.accounts.find(account=>account.id===event.account_id)?.name||"Income account"} · {event.detail}</span></div><div className="event-amount"><strong>+<Money value={event.amount}/></strong><span className={`income-status ${event.income_status}`}>{incomeLabels[event.income_status||"estimated"]}</span></div><span className="row-arrow"/> </div>:<a className={`timeline-row${rowState(event.date)}`} href={`/monthly-plan?month=${event.date.slice(0,7)}&payment=${event.id}&returnTo=%2Ftoday${event.coverage_status==="needs_confirmation"?"&action=match":""}#payment-${event.id}`} onClick={e=>{if(event.coverage_status==="needs_confirmation"){e.preventDefault();setMatchError("");setMatching({id:event.id,payee:event.name})}}}><div className="date-box"><b>{formatDate(event.date,{day:"numeric"})}</b><span>{formatDate(event.date,{month:"short"})}</span></div><div className="timeline-dot"><i/><span/></div><div className="event-main"><strong>{event.name}</strong><span>{data.accounts.find(account=>account.id===event.account_id)?.name||"Funding account needed"} · {event.detail}</span></div><div className="event-amount"><strong>-<Money value={event.amount}/></strong>{event.coverage_status&&<Status value={event.coverage_status}/>} {event.balance_after!==null&&event.balance_after!==undefined&&<small>Projected <Money value={event.balance_after}/></small>}</div><ChevronRight className="row-arrow"/></a>}</Fragment>)}{todayMarkerIndex===flow.length&&todayMarker}</div></section>
      <aside className="right-stack"><section className="panel attention"><div className="panel-head"><div><h2>Needs attention</h2><p>{attention} items may need a decision this month</p></div><span className="attention-count">{attention}</span></div>{data.payments.filter(payment=>!["covered","covered_but_tight"].includes(payment.coverage_status)).slice(0,4).map(payment=><a href={`/monthly-plan?month=${payment.withdrawal_date.slice(0,7)}&payment=${payment.id}&returnTo=%2Ftoday${payment.coverage_status==="needs_confirmation"?"&action=match":""}#payment-${payment.id}`} className="attention-item" key={payment.id} onClick={e=>{if(payment.coverage_status==="needs_confirmation"){e.preventDefault();setMatchError("");setMatching({id:payment.id,payee:payment.payee})}}}><AlertIcon/><div><strong>{payment.payee}</strong><p>{payment.reason}</p><span>Review payment <ChevronRight size={14}/></span></div></a>)}{attention===0&&<div className="empty compact"><ShieldCheck/><p>No decisions needed this month.</p></div>}</section>{data.subscriptions.length>0&&<section className="panel upcoming-renewals"><div className="panel-head"><div><h2>Upcoming renewals</h2><p>Confirmed recurring charges this month</p></div><Repeat2/></div>{data.subscriptions.slice(0,4).map(row=><a href="/monthly-plan#subscriptions" className="renewal-row" key={row.id}><div><strong>{row.name}</strong><p>{formatDate(row.next_expected,{month:"short",day:"numeric"})} · {row.account_name}</p></div><span><Money value={row.typical_amount}/><ChevronRight/></span></a>)}</section>}<section className="panel suggestion"><div className="spark"><Sparkles/></div><div><h3>A safer next step</h3><p>Review payment dates before using flexible cash. FinLeash will never move money without your approval.</p><a href="/monthly-plan">Open Monthly Payment Plan <ArrowRight size={14}/></a></div></section></aside>
    </div>
    <section className="panel account-strip"><div className="panel-head"><div><h2>Account outlook</h2><p>Each payment is funded only from its selected account</p></div></div><div className="account-cards">{data.accounts.map(account=><article key={account.id}><div><span className="bank-icon"><Landmark/></span><div><strong>{account.name}</strong><p>•••• {account.mask}</p></div></div><div><span>Available now</span><strong><Money value={account.available_balance}/></strong></div><div><span>Protected</span><strong><Money value={account.reserve}/></strong></div></article>)}</div></section>
    {matching&&<Dialog title={"Match "+matching.payee} onClose={()=>setMatching(null)} className="match-dialog"><div className="modal-head"><div><p className="eyebrow">Confirm payment</p><h2>Match a bank transaction</h2><p>Choose the posted debit that paid {matching.payee}.</p></div><button className="icon-button" onClick={()=>setMatching(null)}><X/></button></div>{matchError&&<div className="error-box">{matchError}</div>}<div className="match-list">{candidates.data?.map(row=><button className="match-row" key={row.id} onClick={()=>confirmMatch.mutate(row)}><span><strong>{row.merchant}</strong><small>{row.account_name}</small></span><span>{row.date}<small>{row.reason}</small>{!row.account_matches&&<small className="account-change-note">Use {row.account_name} as the funding account</small>}</span><Money value={row.amount}/></button>)}</div></Dialog>}
  </Shell>
}

function AlertIcon(){return <span className="alert-mini"><Info size={16}/></span>}
